"""empty message

Revision ID: d201a9e78f4f
Revises: 7f4bd137757e
Create Date: 2024-03-22 18:35:26.616655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd201a9e78f4f'
down_revision = '7f4bd137757e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('orbital_period', sa.Integer(), nullable=True),
    sa.Column('lenght', sa.Float(), nullable=True),
    sa.Column('gavity', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=50), nullable=True),
    sa.Column('terrain', sa.String(length=50), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites'], ['favorites.fav_id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lenght', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gavity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('climate', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('terrain', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('surface_water', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorites', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorites'], ['favorites.fav_id'], name='planets_favorites_fkey'),
    sa.PrimaryKeyConstraint('uid', name='planets_pkey')
    )
    op.drop_table('planet')
    # ### end Alembic commands ###
